language: java

deploy:
  provider: releases
  api_key:
    secure: "${OAUTH_TOKEN}"
  file_glob: true
  skip_cleanup: true
  file: "target/reddit-wallpaper-downloader-jar-with-dependencies.jarr"
  on:
    repo: MoriTanosuke/reddit-wallpaper-downloader
tags: true
